[package]
name = "laba5"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "task1"
path = "src/task1.rs"


[[bin]]
name = "task2"
path = "src/task2.rs"


[dependencies]

rand = "0.8.5"